(function(d){var h=[];d.loadImages=function(a,e){"string"==typeof a&&(a=[a]);for(var f=a.length,g=0,b=0;b<f;b++){var c=document.createElement("img");c.onload=function(){g++;g==f&&d.isFunction(e)&&e()};c.src=a[b];h.push(c)}}})(window.jQuery);
var wl;

ldsrcset=function(t){var e,r=document.querySelectorAll(t);for(e=0;e<r.length;e++){var c=r[e].getAttribute("data-srcset");r[e].setAttribute("srcset",c)}},ldsrc=function(t){var e=document.querySelector(t),r=e.getAttribute("data-src");e.setAttribute("src",r)};!function(){if("Promise"in window&&void 0!==window.performance){var e,t,r=document,n=function(){return r.createElement("link")},o=new Set,a=n(),i=a.relList&&a.relList.supports&&a.relList.supports("prefetch"),s=location.href.replace(/#[^#]+$/,"");o.add(s);var c=function(e){var t=location,r="http:",n="https:";if(e&&e.href&&e.origin==t.origin&&[r,n].includes(e.protocol)&&(e.protocol!=r||t.protocol!=n)){var o=e.pathname;if(!(e.hash&&o+e.search==t.pathname+t.search||"?preload=no"==e.search.substr(-11)||".html"!=o.substr(-5)&&".html"!=o.substr(-5)&&"/"!=o.substr(-1)))return!0}},u=function(e){var t=e.replace(/#[^#]+$/,"");if(!o.has(t)){if(i){var a=n();a.rel="prefetch",a.href=t,r.head.appendChild(a)}else{var s=new XMLHttpRequest;s.open("GET",t,s.withCredentials=!0),s.send()}o.add(t)}},p=function(e){return e.target.closest("a")},f=function(t){var r=t.relatedTarget;r&&p(t)==r.closest("a")||e&&(clearTimeout(e),e=void 0)},d={capture:!0,passive:!0};r.addEventListener("touchstart",function(e){t=performance.now();var r=p(e);c(r)&&u(r.href)},d),r.addEventListener("mouseover",function(r){if(!(performance.now()-t<1200)){var n=p(r);c(n)&&(n.addEventListener("mouseout",f,{passive:!0}),e=setTimeout(function(){u(n.href),e=void 0},80))}},d)}}();

$(function(){
r=function(){dpi=window.devicePixelRatio;var a='data-src';var e=document.querySelector('.js4');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?'images/home-1080-1084.jpg':'images/home-1080-542.jpg');
var a='data-src';var e=document.querySelector('.js5');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?'images/mygov2025-v03-p1-all-scenarios-1080-1084.jpg':'images/mygov2025-v03-p1-all-scenarios-1080-542.jpg');
var a='data-src';var e=document.querySelector('.js6');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?'images/stylemanual-1080-1084.jpg':'images/stylemanual-1080-542.jpg');
var a='data-src';var e=document.querySelector('.js7');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?'images/careerpathfinder-1080-1084.jpg':'images/careerpathfinder-1080-542.jpg');
var a='data-src';var e=document.querySelector('.js8');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?'images/elp-cadet-page-758.png':'images/elp-cadet-page-379.png');
var a='data-src';var e=document.querySelector('.js9');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?'images/digital-profession-early-mockup-1880-1226.png':'images/digital-profession-early-mockup-1880-613.png');
var a='data-src';var e=document.querySelector('.js10 .slide0');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?'images/desktop-1-1560-1366.png':'images/desktop-1-1560-683.png');
var a='data-src';var e=document.querySelector('.js10 .slide1');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?'images/desktop-2-1560-1366.png':'images/desktop-2-1560-683.png');
var a='data-src';var e=document.querySelector('.js10 .slide2');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?'images/desktop-3-1560-1366.png':'images/desktop-3-1560-683.png');
var a='data-src';var e=document.querySelector('.js10 .slide3');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?'images/desktop-4-1560-1366.png':'images/desktop-4-1560-683.png');
var a='data-src';var e=document.querySelector('.js10 .slide4');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?'images/desktop-5-1560-1366.png':'images/desktop-5-1560-683.png');
var a='data-src';var e=document.querySelector('.js10 .slide5');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?'images/desktop-6-1560-1366.png':'images/desktop-6-1560-683.png');
var a='data-src';var e=document.querySelector('.js11');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?'images/playsmockup-1640.jpg':'images/playsmockup-820.jpg');
var e=document.querySelector('.js1');e.setAttribute('src',(dpi>1)?'images/me-headshot-360-366.jpg':'images/me-headshot-360-183.jpg');
var e=document.querySelector('.js2');e.setAttribute('src',(dpi>1)?'images/3-column-feature-section-image-variation-572.png':'images/3-column-feature-section-image-variation-286.png');
var e=document.querySelector('.js3');e.setAttribute('src',(dpi>1)?'images/playbookprototype-1084.jpg':'images/playbookprototype-542.jpg');};
if(!window.HTMLPictureElement){r();}
(function(){$('a[href^="#"]:not(.allowConsent,.noConsent,.denyConsent,.removeConsent)').each(function(i,e){$(e).click(function(){var t=e.hash.length>1?$('[name="'+e.hash.slice(1)+'"]').offset().top:0;return $("html, body").animate({scrollTop:t},400),!1})})})();
ldsrcset('.js12 source');ldsrcset('.js13 source');ldsrcset('.js14 source');ldsrcset('.js15 source');ldsrcset('.js16 source');ldsrcset('.js17 source');$('.js10 .slider').slick({lazyLoad: 'ondemand',slidesToShow: 1,slidesToScroll: 1,overflow: 'hidden',fade: true,slide: 'div',cssEase: 'linear',speed: 300,dots: false,arrows: true,infinite: true});ldsrcset('.js18 source');if(location.hash){var o=location.hash.replace('#',''),e=function(){if(document.body.getBoundingClientRect().top>0){var t=document.querySelectorAll('[name="'+o+'"]')[0];t&&t.scrollIntoView(!0),setTimeout(e,100)}};e()}
});